### PR TITLE
domains dataset, used in multiple notebooks

### PR DESCRIPTION
**Pull request by sbenthall**
This PR models a solution to #509 by putting the known email domain categorization metadata in a `datasets` section of the `bigbang` module. This is now potentially documented in the autodocs that go to the RTD website. The same dataset submodule can then be used across multiple notebooks.

For this PR, some remaining work:
 - When I get the full IETF mailing list history loaded, will update the `Full Archive Study` and `Classifying Email Domains` notebooks
 - Add the autodocs for this dataset and further documentation in the appropriate part of the RTD section.

The idea is that this models what can be done with other data we package with BigBang, such as the organizational metadata collected by @nllz

### CODE REVIEW

**Comment by sbenthall** [comment]
See also #437

**Comment by Christovis** [comment]
The new file `datasets/domains/all_email_provider_domains.txt` contains all email domains found in the IETF datatracker correct? I guess I should scan over them and add any that appear in 3GPP but are currently missing?

**Review by Christovis — COMMENTED** [review]
We can merge it as is.

**Comment by sbenthall** [comment]
> The new file `datasets/domains/all_email_provider_domains.txt` contains all email domains found in the IETF datatracker correct? I guess I should scan over them and add any that appear in 3GPP but are currently missing?

No, it does not contain all those domains.
It contains only domains that have been identified as generic email address domains.
These get combined with another list of domains of known categories (which is much shorter).

It's a good point that I should document this more carefully. I'll do that before merging.

**Pull request merged**
