### PR TITLE
tenure calculation script and debugging improvements

### PR DESCRIPTION
**Pull request by npdoty**
The script `tenure.py` in `bin` handles calculation of earliest date, latest date and total messages for participants in large numbers of subdirectories archives for different lists.

This also integrates some improvements in debugging and logging in the `mailman` and `parse` library files.

### CODE REVIEW

**Comment by npdoty** [comment]
The debugging improvements partly address #353

**Comment by sbenthall** [comment]
Beautiful looking code. Love the improvements to logging (as opposed to pretty print).

Starting to test now.

**Comment by sbenthall** [comment]
My first attempts to use the script based on the documentation available didn't work:

```
$ python2 bin/tenure.py --archives archives/hrpc/


```
```
$ python2 bin/tenure.py --archives archives/ipython-dev/


```

This is pointing the `--archives` argument into a directory with `.mail` archive files:

```
$ ls archives/hrpc
2014-10.mail  2015-04.mail  2015-10.mail  2016-04.mail  2016-10.mail  2017-04.mail  2017-10.mail  2018-04.mail
2014-11.mail  2015-05.mail  2015-11.mail  2016-05.mail  2016-11.mail  2017-05.mail  2017-11.mail  2018-05.mail
2014-12.mail  2015-06.mail  2015-12.mail  2016-06.mail  2016-12.mail  2017-06.mail  2017-12.mail  2018-06.mail
2015-01.mail  2015-07.mail  2016-01.mail  2016-07.mail  2017-01.mail  2017-07.mail  2018-01.mail  2018-07.mail
2015-02.mail  2015-08.mail  2016-02.mail  2016-08.mail  2017-02.mail  2017-08.mail  2018-02.mail  provenance.yaml
2015-03.mail  2015-09.mail  2016-03.mail  2016-09.mail  2017-03.mail  2017-09.mail  2018-03.mail
```
When I point the `--archives` option at the next higher directory up (`archives/`), it runs more or less as expected and creates  `*-tenure.csv` files in the corresponding directory.

Could you provide some clarity of what's going on in the documentation, or else allow for pointing at a subdirectory?

**Comment by sbenthall** [comment]
Would it be possible to document the units of the Earliest Date and Latest Date columns of `*-tenure.csv`. I'm assuming these are something like days-since-epoch, but i imagining fishing around for that would be unfun. Alternatively, you could store these in a more human-readable date format in the .csv

**Comment by npdoty** [comment]
@sbenthall the date format is the "proleptic Gregorian ordinal of the date", that is, the output of `datetime.toordinal()` [datetime docs](https://docs.python.org/2/library/datetime.html#datetime.date.toordinal). I believe that's the format we're using in the activity frame as well, so it's pretty common in bigbang. I agree it would be good to document: where do you think that should be? In the `tenure.py` help text?

**Comment by npdoty** [comment]
@sbenthall the help for the script tries to imply that the archives parameter contains subdirectories with archives for different lists, but I'd welcome clarifications on that since it wasn't immediately obvious.
> Provide the path to a directory of archives, containing subdirectories for each mailing list.
Or perhaps we could modify the script so that it tried to guess whether it was inside a single mailing list's archive directory or in a parent directory and adjust its behavior. But I feel like that might be a little too magical or error prone.

**Comment by sbenthall** [comment]
Hi @npdoty . Revisiting this PR after... a year! yikes.

To answer your questions: 
 - yes, the tenure.py help text would be a good place to put that note
 - nevermind about the directory issue--I probably just didn't see the help text.

This is good to merge as-is. But in case you felt like fixing the docs issue just to make it squeaky clean, I'll wait a couple days before the merge.

**Pull request merged**
