### PR TITLE
Just a little cleanup of old files

### PR DESCRIPTION
**Pull request by MridulS**
- removed flake8, use ruff instead as part of pre-commit with pyproject.toml to hold the config
- removed travis config file
- move isort config to pyproject.toml
- updated black version
- removed get_dependencies.py, it's not used anywhere and depends on unsupported project
- Should we just remove setup.py file? I don't think there is a need. The information is already present in pyproject and the only thing is the custom pre-commit command. Maybe we shouldn't have a custom command for this? The developer just needs to do `pre-commit install` after cloning bigbang and this could be documented. (Less the code the better :) )

### CODE REVIEW

**Comment by MridulS** [comment]
Well the minor cleanup went on to become major one:

In this PR I have removed env.yaml/conda-setup/requirements.txt, I also have a feedstock request https://github.com/MridulS/staged-recipes/tree/bigbangpy_on_conda_forge which will let users do `conda install bigbang-py` but this would first require a fixed pypi distribution.

**Comment by MridulS** [comment]
In https://github.com/datactive/bigbang/pull/579/commits/46693a209cf4c0f2b3b93eb7cf6317ac75d77848 I have run black on all the files with the latest release of black + black default config to make the lint checks on github actions happy. This has added a lot more changes to this PR, I can use a different PR to put the black changes so it can be a bit more cleaner while reviewing this PR.

**Comment by sbenthall** [comment]
Thank you for all this great work!

I agree that removing setup.py and updating the docs is best.

Does this PR interact with #578 ?

**Comment by MridulS** [comment]
>Does this PR interact with https://github.com/datactive/bigbang/issues/578 ? 

Yes, I will try to fix both https://github.com/datactive/bigbang/issues/578 and #577 in this PR so we have clean pypi/conda install.

**Comment by sbenthall** [comment]
Hoorah!

**Comment by MridulS** [comment]
Ahhh, should have marked it WIP. I haven't checked everything. I will continue in a new PR

**Comment by sbenthall** [comment]
My apologies....

**Pull request merged**
