### PR TITLE
add name/email/affilation timed relation extraction to notebook, see …

### PR DESCRIPTION
**Pull request by sbenthall**
This PR addresses #25 and #367

Currently just an implementation in a notebook, but it can be moved to the library if it looks more generally useful.

The main insight here is with respect to the data format for this relational data as per #367 

The IETF attendance data is mined for three tables data, with the following columns:

 - (A) full_name, affiliation, min_date, max_date
 - (B) email, affiliation, min_date, max_date
 - (C) full_name, email, min_date, max_date

Table B can then be used directly to solve issue #25 : for each email/timestamp in the email data, look up up the email on table B for its affiliation. If there is more than one row, find the row with the best matching time duration.

[Writing this matching script is another TODO for this PR]

Of course, a similar analysis could be done using (A) and matching on full names, though this is likely to have more noise than the free text name entry. The other data is extracted for completeness and to support further downstream entity resolution on names, email addresses, and affinities.

If this approach gets approval, then there are a few remaining issues for this PR:
 - [x] The matching script from table B to a mailing list
 - [x] Work in (optional?) entity resolution on affiliations
 - [x] Move these functions into the library
 - [ ] Automated tests?

### CODE REVIEW

**Comment by Christovis** [comment]
I think this is great work and we should follow this approach.
And the inference from the available data points to dates that are not explicitly represented in the data  that is implemented is fine for now, until we see that we need to improve it...

**Comment by sbenthall** [comment]
I'm not sure how to go about automated tests for functionality that wraps the IETF DataTracker, as that pings an external service and can run rather slowly.

**Comment by sbenthall** [comment]
Tests are passing.
As I mentioned, I'm not sure the best way to proceed with testing of fucntionality that wraps the Glasgow IETF datatracker tool...

The notebook shows how to use the IETF attendance data to fill in affiliations for an archive.
It has some functions in it that could potentially be moved to the library.

For now, I'll request a review of this current work.

**Comment by sbenthall** [comment]
Automated test for merging affiliation into Archive data is in. Request review from @Christovis

**Pull request merged**
