### PR TITLE
new cleaned notebooks - optimized for IETF lists

### PR DESCRIPTION
**Pull request by nllz**
Notebooks produced during IETF101 hackathon. These notebooks are an improvement of the summerschool notebooks, and which were already largely a consolidation of other notebooks. So this should largely tackle  
#271. 

Perhaps we can move the other notebooks that are replace by this to an archive folder?

### CODE REVIEW

**Comment by sbenthall** [comment]
I'm beginning to review this change.

My first observation: these changes make new notebooks in subdirectories of the `examples` directory: `examples/network_analysis`, `examples/threads_analysis`, and so on. I believe these are modified versions of the notebooks named `SummerSchool*` in the top level `examples` directory.

As part of the effort to "garden" the notebooks #271 , I think this pull request should remove the SummerSchool notebooks, which these new cleaner notebooks make redundant.

**Comment by sbenthall** [comment]
I notice that these notebooks use the data-loading style of the summer school notebooks, which involves hard-coding the archive directory path into the notebook.

While I don't think it should block the PR, I want to note that ideally all notebooks will be changed to use the configured archive directory. See #113 and #309

**Comment by sbenthall** [comment]
I am having trouble running some of the notebooks for the mundane reason that I don't seem to have the right data in the right format in the right location.

Are there any kind of setup instructions associated with these notebooks?

Would it be possible to include a link to that documentation in the notebook themselves? Or else to include it as a README in the examples file?

If such a thing already exists and I'm blind to it, please forgive me.

**Comment by nllz** [comment]
@sbenthall do you mean you don't have the 6lo list for instance in the archives folder? notebooks should work with every list in there.

**Comment by nllz** [comment]
@sbenthall Agree on removing summerschool notebooks, and probably move the notebooks that are now in folders to the examples directory and change their names a bit. Anyone wants to jump on a call and brainstorm different ordering/gardening strategies?

**Comment by sbenthall** [comment]
I'm about to get on a plane to a conference. Meeting before Thursday would
be hard. But a meeting then would be good. Can we coordinate by email?

But to remove the Summer School files from your branch and add that change
to the pull request, you can use these commands:

https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-git-repo

I think this change can be made independently of the new archive directory
configuration.

**Comment by nllz** [comment]
Can this be pulled now, or are the still issues?

**Comment by sbenthall** [comment]
Yes, OK, I see that #324 addressed the question of the summer school notebooks. I'll merge this now.

**Pull request merged**
