### PR TITLE
Adding entity recognition and example notebook

### PR DESCRIPTION
**Pull request by effyli**
Adding a named entity recognition method with huggingface. Adding an example notebook on how to use the recognizer with emails and visualize the recognized entities.

### CODE REVIEW

**Comment by sbenthall** [comment]
Thanks for this PR!

The failing test seems to be unrelated -- it's due to deprecation in some dependencies:
https://github.com/scverse/anndata/commit/7b1077d5e1a63fef0d47d716d19ea14ad2ad10de

Once I've gotten this test fixed I'll merge this PR.

**Comment by sbenthall** [comment]
Does this code have any additional dependencies not yet included in `requirements.txt`?

**Comment by sbenthall** [comment]
```
import transformers[torch]
import contractions
import spacy
```

**Comment by Christovis** [comment]
As this is still in an early experimental stage, I would opt for not merging it for now and wait until this work has more matured.

**Pull request closed without merging**
