### PR TITLE
Adding NER model and pre-processed results in the notebook

### PR DESCRIPTION
**Pull request by effyli**
A few things to note:

- The requirements still need to be changed.
- Only need to run the last cell in the notebook to display pre-processed entities for mailing list 3gv6. If for display only, then no new packages need to be installed.

### CODE REVIEW

**Comment by sbenthall** [comment]
Tests are failing because dependencies have not been updated, it seems.

There may also be a merge conflict with recent changes to `main`.

**Comment by sbenthall** [comment]
@effli Thanks for this PR! Sorry for the very slow review turnaround.

This will be a great addition to BigBang. The only issue I'm getting is an error in cell 14.
You are using the `append()` method of a Pandas DataFrame. But this is a deprecated feature that has been removed in the most recent version:

https://stackoverflow.com/questions/75956209/dataframe-object-has-no-attribute-append

Could you please update the Pandas version you have installed and correct this code? Otherwise, this PR is good to merge.

**Comment by effyli** [comment]
Hi Seb,

Thanks for checking my PR! I have fixed the problem and re-pushed the code.

Best,
Effy

Best,
Effy

**Comment by sbenthall** [comment]
Thanks @effyli great work!

**Pull request merged**
