### PR TITLE
 Integrate listserv 16.5 ingress into standard collect_mail.py

### PR DESCRIPTION
**Pull request by Christovis**
This PR should address #419 . 
It takes however very long to ingest the Listserv archive. This might motivate rethinking the current strategy.

### CODE REVIEW

**Comment by sbenthall** [comment]
I'm still getting errors from the `input()` statements in the listserv tests, I think?
https://gist.github.com/sbenthall/4aff3ce1fdb9a0f2b21e9cc2de0ee1ea

**Comment by Christovis** [comment]
The new commit should fix it.
Sorry for this.

**Comment by sbenthall** [comment]
I'm getting test failures on this from what seem to me like a network timeout issue.

https://gist.github.com/sbenthall/5970cbaa17ed78914920bc84d878aa52

Trying again, it looks like they pass. This means they pass intermittently.

While I understand it in a sense limits the coverage of the tests, I think it's a good idea for our unit tests at this stage to run locally without pinging external servers. If our unit tests cannot be passed reliably under even spotty network conditions, it will be harder to use them as an anchor to our development process.

Would it be possible to just remove these failing tests? That is, if their failures aren't exposing some problem with the underlying code.

I'm open to other points of view on this and am curious what @npdoty thinks.

This is also related to #411 . I.e., do we want automated code coverage tools to be firing false negatives due to network issues? How do we integrate this into our process?

Thanks @Christovis for all the work you've done on this. Please don't take my hesitations here as criticism. Rather, you've pushed the project in a new way that is making us consider our testing policy in new ways. Thanks.

**Comment by sbenthall** [comment]
Ok. So, what I'm thinking is:
 - #443 will solve the intermittent testing issue.
 - there's no reason to block this PR because of this known network issue.
Merging!

**Pull request merged**
