### PR TITLE
demonstration of name and gender estimation for a mailing list

### PR DESCRIPTION
**Pull request by npdoty**
Addressing the feature request in #249, this adds some name-guessing functionality to the parse library and provides a Notebook that walks through basic automated gender estimation, manual gender estimation, a simple workflow (input/output of CSVs) for adding manual data, and a comparison between the two for a mailing list.

In the process, I also fixed a few issues I hadn't previously discovered with W3C mailing list crawling and a feature for specifying an archives directory.

### CODE REVIEW

**Comment by sbenthall** [comment]
Would you mind telling me what steps I should take to test this new functionality?

I plan to do a thorough code review (sorry for the delay!) but some advice about where to start testing would be helpful.

**Comment by npdoty** [comment]
@sbenthall sure! The changes to shared libraries are largely the following:
* command line option to set the archives directory for storing collected archives
* minor troubleshooting fixes on handling URLs for collection
* added a function for extracting names from From headers
* lexical distance parameter for entity resolution

You should be able to test the collection functionality just by running the collect_mail script and trying its new ``--archives`` option. The lexical distance piece (I hadn't intended that to originally be part of this PR, but it's an update I've made since that could be generally useful) is a parameter passed through to `resolve_sender_entities`; it's a new parameter so it shouldn't affect any existing code, but you can try it with the `w3c-demographics/Entity Resolution` Jupyter notebook.

The main addition in this PR is the name/gender testing, and that's mostly done in the Jupyter notebooks. `examples/Analyze Senders - Name and Gender.ipynb` is the primary one to look at there.

I didn't realize that the pull request would automatically include all additional commits that I pushed to the branch on my own repository, so this now includes some other notebooks and data from work I'm doing in the `w3c-demographics` folder, which isn't necessarily of general interest. We can change the PR to exclude those commits.

**Comment by sbenthall** [comment]
Ok, I'm checking this out.

First comment: it looks like there are some project specific example in the `examples` directory.

It's a little messy in there, probably not on purpose, but maybe it is a good showcase of the variety of things one can do with the project?

Your `w3c-demographics` folder could go in there if you felt it was something you felt was a good example of the functionality.

Alternatively, if it feels like too much of a loose end to you, you could remove it.

I'm +0 either way, but think we should have a discussion of what we want in the examples directory.

**Comment by sbenthall** [comment]
I've tried collecting the w3c group emails with this command:

`python2 bin/collect_mail.py -f examples/w3c-groups/w3c-current-groups.tsv --archives w3c`

I got the following error:

https://gist.github.com/sbenthall/79237541b6ddb9145f61f136dade0265

Is this expected? I may not be using the file as intended. (I used python2 here because Python 3 is now the default on my computer).

As you are now one of the main users of this software, I'd be strongly in favor of making the default usage (i.e. documentation, examples) reflect W3C analysis more.

I see there's a long standing ticket #278 which would generalize its SciPy focus from simply SciPy to all of Python.

**Comment by npdoty** [comment]
@sbenthall that error is from using the `w3c-current-groups.tsv` file, which is mostly for human consumption. The same command but with `w3c-current-lists.txt` should work properly; the latter contains just URLs, not the names of groups or categorization like Working Group and Interest Group, and matches existing `collect_mail.py` behavior.

**Comment by npdoty** [comment]
@sbenthall yeah, I was really unsure about whether to include my own research examples in the examples folder of this repository vs. a separate folder of this repository vs. an entirely separate repository altogether.

I suppose that ideally our own branches would contain research-specific files, but that some set of shared directories and the pull requests that we contribute back would contain a minimum of that. I did think having a list of W3C current groups might be useful for other researchers, so I included it intentionally in `examples`, but I agree that we should settle on guidance for what kind of things we want there.

**Comment by sbenthall** [comment]
@npdoty Having slept on it...I'm thinking it would definitely be good to have *something* in the examples directory demonstrating the functionality.

Realistically, every notebook in the examples directory is somebody's specific research. We haven't had the resources to create demos that are not opportunistic.

Maybe we should start a practice of organizing the examples directory with more structure. Directories with READMEs to setup and test the functionality, for example.

**Comment by sbenthall** [comment]
Ok, the data collection script appears to be working for `w3c-current-lists.txt`

I would say that if `w3c-current-groups.tsv` is not being used to prepare any notebooks in `examples`, it should be removed.

Maybe it could be replaced with `w3c-current-lists.txt`? There are other .txt files with URLs in that directory.

**Comment by npdoty** [comment]
in ff3adc1 I've tried to re-organize the files so that there is a coherent directory structure for this under `examples` and that other files are moved to separate `w3c-demographics`.

**Comment by sbenthall** [comment]
So, I have been running this command for the better part of the day:

`python2 bin/collect_mail.py -f w3c-demographics/w3c-current-lists.txt --archives w3c`

At some point it started to hang, and I wasn't sure whether it was because it was just taking a long time to download the next archive or if there was actually a problem (either with the code or with the server it's fetching the archive from). So I tried killing the program and starting again.

It looks like when I do this, it starts downloading every single file again from scratch. That's going to make it tricky to debug this script to see if it's a case of the server or what.

I wonder if it would be possible to test for the existence of an archive file before downloading it again, speeding up the processing in case the user has to restart the script for whatever reason (dodgy wifi would be another.)

**Comment by npdoty** [comment]
Yeah, downloading the full archives of an entire standard-setting body is quite a large undertaking. It took me several days, including a few restarts, running in a process on a shared server. W3C collection is particularly slow because we download one message at a time since full .mbox archives aren't provided by the archive service. That's one reason we're separately pursuing data archives so that researchers can share that burden and quickly clone a large number of mail archives rather than collecting them.

Issue #282 describes improvements for error handling during mail collection, and I'd appreciate any further suggestions there. I believe `collect_mail.py` should already check for the existence of saved .mbox files and not repeat those, although it still has to crawl the archive thread pages to figure out which archives are present before it tests month by month to see if the saved .mbox files are there.

**Comment by sbenthall** [comment]
Ok, roger that on the mail collection. There's a lot going on there and it shouldn't block this great PR.

Moving on...

I'm testing the Jupyter notebook titled "Analyze Senders - Name and Gender" in `examples/name-and-gender`. Running cell 2 gets me the following error:

`ImportError: No module named gender_detector`

I've grepped for the text "gender_detector" and "GenderDetector" in the project directory and it appears only in the notebook. Which makes me think either the code isn't checked in or the notebook code is out of sync with what has been checked in.

**Comment by sbenthall** [comment]
I have to say your data visualizations are really nice, aesthetically. I like the use of color.

**Comment by npdoty** [comment]
@sbenthall ah, `gender_detector` is an external dependency. There's no missing code, it's just something that needs to be installed on the machine; it's the library referenced in #249.

Does that need to be added to requirements.txt for the whole project? Or should I document in the notebook that you need to run `pip install gender-detector`?

**Comment by sbenthall** [comment]
I think we should consider gender detection to be core part of BigBang functionality. It's a great feature.
That means we should include the dependency. 

requirements.txt is for pip installation.
conda-requirements.txt is for conda installation

I think it should be added to both, though I believe on the conda end there's been some significant changes (it's now anacondacloud.com instead of binstar I believe) and I wonder if that breaks the build.

**Comment by npdoty** [comment]
I've pushed a commit to add `gender-detector` to both requirements files, but I can't test/confirm the conda version.

**Comment by sbenthall** [comment]
Hey Nick. So I tested the Conda installation and couldn't get it to work as written. This commit has a fix that seems to work.

https://github.com/sbenthall/bigbang/commit/f09902cd128ddaae14f1ad09de2f71f21c39b865

You can make that change yourself or maybe you can find a way to bring it into your branch with `git cherry-pick`

In the meantime, I'm trying to test the functionality. What I'm seeing is that the W3C Groups, Participation, and Gender notebook has by default many, many mailing lists listed. I see why that's important for your analysis. I wonder if it would make sense to use a more limited set for the purposes of testing and demonstration.

**Comment by npdoty** [comment]
Cherry-picked conda installation fixes from @sbenthall.

**Comment by npdoty** [comment]
I'm trying to make the distinction between testing/demonstration in the `examples` directory and full demographics research in the top-level `w3c-demographics` directory. I agree that many mailing lists makes it harder to test, so the example just uses 1 or 2.

If we don't want any notebooks with the full set of W3C groups and comparison data, I could move that Python notebook out of the bigbang repo altogether (or at least, out of the parts that I'm submitting as pull requests back to datactive). I'm not sure we've settled on whether/how to include our ongoing research in Bigbang, and I'm open to suggestions. In any case, I'm eager to get PRs merged so that we can build off each other's work, though.

I'm not sure you need to test every step of that longer w3c-demographics notebook in order to merge it in as useful for others doing that research. If you want to, I can give you access to a repo of all the mail archives already downloaded so that you don't have to babysit that multi-day process.

**Comment by npdoty** [comment]
Per our teleconference, we're planning to keep files/commits for scientific inquiry out of datactive:master and instead develop those in our own forks. To that end, I've removed (in 52eef78) the separate top-level `w3c-demographics` directory from this PR, which should make it less confusing for those people using BigBang but not interested in seeing that research or associated files. I'll continue that progress on additional branches at npdoty/bigbang.

This should also make it faster to review and merge this PR.

**Comment by sbenthall** [comment]
In the third cell of the notebook, I think the line should be:

`mlists = [(url, mailman.open_list_archives(url,"../../archives")) for url in urls]`

because the notebook is nested one directory deeper and so needs an extra `../`

**Comment by sbenthall** [comment]
Otherwise, looks ready to merge.

**Comment by sbenthall** [comment]
May I make this change?

**Comment by sbenthall** [comment]
MERGED!
I'm ecstatic!

**Pull request merged**
