### PR TITLE
LISTSERV 16.5 url lists to /examples/url_collections/

### PR DESCRIPTION
**Pull request by Christovis**
This PR will:
- add `/examples/url_collections/listserv.3GPP.txt`
- add method to `/bigbang/listserv.py` to generate the above
- new handling of corner cases (e.g. missing date) in `ListservMessage.format_header_content()`
- add better docstrings to `/bigbang/listserv.py`  in some places
- adjust `tests/webscraping/test_listserv.py` for renaming of some variables and include larger number of mailing list to make sure that corner cases named above are included and tested for

### CODE REVIEW

**Comment by sbenthall** [comment]
Hello. Thanks for this PR. Sorry for the slow response -- I've been up against a major major deadline this week.

I'm getting some failing tests. I wonder what's up.

https://gist.github.com/sbenthall/8e0110c01e821fa127bc0c20bf3007af

**Comment by Christovis** [comment]
Tststs... sorry about that. The latest commit should fix the issue. The issues was:
1) I overlooked in a @classmethod to address a class object properly: cls.empty_header
2) Didn't take proper care of a corner case in which an Email header does not contain a date

**Comment by sbenthall** [comment]
Still getting test failures.

Looks like something about connections being tried, and retried, and retried, then aborted.

Is this pinging an external server?
https://gist.github.com/sbenthall/29486b79ca7ea014f07e4f59e69391ec

**Comment by Christovis** [comment]
Yes, the webscraping tests require a good internet connection and can take much longer than the tests in `/tests/unit/` (take ~5min for me). It is very probable that the error is caused by a weak connection. Maybe Nick can try as it [worked](https://github.com/datactive/bigbang/pull/443#pullrequestreview-612754624) for him the last time (it is working for me).

**Comment by sbenthall** [comment]
Ok it passed for me this time!

**Pull request merged**
