### PR TITLE
notebook gardening as per issue #271

### PR DESCRIPTION
**Pull request by nllz**
Hi all,

I created the following subfolders in examples, namely:
obsolete_notebooks
experimental_notebooks
url_collections

I put the summerschool notebooks in the obsolete folder, the ones that we haven't re-tested in expirimental and the lists or urls in url_collections.

The way we can go through putting notebook from expirimental in a new folder category would be simply going through them, making sure they work and that they use the proper archive reference.

Happy to discuss!

### CODE REVIEW

**Comment by sbenthall** [comment]
Thank you for this. It is excellent.

One question: do we need an obsolete notebooks directory? Can't we just delete them?

**Comment by nllz** [comment]
I rly kinda like having old notebooks, both for reference, institutional memory, etc. 

I know you can also get them back from versioning, but that is a lot more hassle. 

Another reason for having them is maybe for reference in scientific articles, so people can still reproduce the outcomes?

**Comment by nllz** [comment]
This is true when you _know_ what you're looking for, not if you don't exactly know what you're looking for. Maybe @npdoty or @davidberra can weigh in?

**Comment by davidberra** [comment]
i am pro to a obsolete_notebooks folder; just sounds easy and cheap, and would make me feel lighthearted when periodically cleaning up the examples

**Comment by sbenthall** [comment]
Ok...

I think I'm beginning to see the role for an old notebooks directory.

For these notebooks in particular, though, aren't they almost exactly
what's in some of the non-obsolete directories? I.e. they are just slightly
different from the notebooks we intend to keep maintaining.

If we want these notebooks at the top level for sentimental or museum-like
reasons, maybe we should pick a name thats nicer than "obsolete".

Another option would be to *tag* a commit with the summer school notebooks,
specifically so it can be found again. A tag is like a release, but lighter
weight. Just a named commit.

**Comment by npdoty** [comment]
I could live with anything here, but I think tagging a commit that has notebooks and then removing them from master works well. We can point people to those notebooks that were used in the past, but it would be great if most/all notebooks in the master repository worked if someone poked around and tried them, and we don't want to commit ourselves to maintaining a huge list of notebooks. Version control means that history isn't gone even if it's not in the HEAD.

**Pull request merged**
