### PR TITLE
ietfattendance updated, notebook demonstrating use of ietfdata/datatracker

### PR DESCRIPTION
**Pull request by npdoty**
Addresses #424 and #392.

### CODE REVIEW

**Comment by sbenthall** [comment]
In `IETF Attendance` notebook, cell 7, I'm getting the following error:

```
registrations110 = list(regs)
```

**Comment by npdoty** [comment]
@sbenthall yeah, my bad, I pushed some new functionality (in response to IETF leadership requests), but that removed some slower, earlier parts and I need to clean up the notebook so that it works start to finish. I'll request review when that's ready again.

**Comment by sbenthall** [comment]
In cell [18] I'm getting an ImportError

`ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`

Is this a new dependency? I see the note about not using CSV, but I believe it should be possible to render a properly escaped CSV from the Excel file, or else include different arguments to the CSV parser to get it to escape right?

**Comment by npdoty** [comment]
> Is this a new dependency? I see the note about not using CSV, but I believe it should be possible to render a properly escaped CSV from the Excel file, or else include different arguments to the CSV parser to get it to escape right?

That's a good idea. I've removed the .xls file (which would need that additional pip import) and exported a CSV that has the proper quoting around commas, and updated the explanation in the notebook.

**Pull request merged**
