### PR TITLE
Adding gender analysis for drafts to HRPC working group notebook

### PR DESCRIPTION
**Pull request by sbenthall**
image

Adding a gender guess analysis of working group draft productivity.

### CODE REVIEW

**Comment by sbenthall** [comment]
Better: 

image

**Comment by sbenthall** [comment]
For HTTPBIS for comparison

image

Correlations:


  | women | unknown | men | diversity | drafts
-- | -- | -- | -- | -- | --
1.000000 | 0.101518 | 0.129112 | 0.129873 | -0.013933
0.101518 | 1.000000 | 0.944388 | -0.266919 | -0.006669
0.129112 | 0.944388 | 1.000000 | -0.446713 | -0.003329
0.129873 | -0.266919 | -0.446713 | 1.000000 | -0.017534
-0.013933 | -0.006669 | -0.003329 | -0.017534 | 1.000000



p-values:


  | women | unknown | men | diversity | drafts
-- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0.2571
0 | 0 | 0 | 0 | 0.5875
0 | 0 | 0 | 0 | 0.7866
0 | 0 | 0 | 0 | 0.1538
0.2571 | 0.5875 | 0.7866 | 0.1538 | 0

**Comment by sbenthall** [comment]
image

**Comment by sbenthall** [comment]
@nllz it sounds like this is passing your review. I've made #398 for your great point about more interactive gender disambiguation.

I'd like to add one more thing to this PR before merging, which is some documentation in the README about how to use the draft metadata collection script in `bin/` (which would also do a shut out to the Glasgow group)

**Comment by nllz** [comment]
I reviewed it now, sorry to be late. I agree it should be merged.

**Pull request merged**
